
-- .日历表
create table  t_app_calendar(
	id varchar(64) generated by default as identity, --主键
	userid varchar(64), --用户编号
	title varchar(255) not null,
	details varchar(255),
	startdate varchar(64),
	length int,
	starttime varchar(64),
	endtime varchar(64),
	backgroundcolor varchar(64),
	textcolor varchar(64),
	primary key (id)
);